version: '3.7'

services:
  web-app:
    build: .
    restart: always
    entrypoint: "/api_app/docker_run/start.sh"
    env_file: .env_web-app
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.4
    container_name: db_app
    env_file: .env_db
    volumes:
       - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    container_name: redis_app

  celery:
    build: .
    container_name: celery_app
    env_file: .env_web-app
    entrypoint: "/api_app/docker_run/celery.sh"
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery_beat_app
    env_file: .env_web-app
    entrypoint: "/api_app/docker_run/celery_beat.sh"
    depends_on:
      - redis

volumes:
  postgres_data: