"""0012_edit_relationships

Revision ID: 387a3f19f8e5
Revises: dbb1a65a8986
Create Date: 2024-09-02 12:11:04.342734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387a3f19f8e5'
down_revision: Union[str, None] = 'dbb1a65a8986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('publication_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorites_car_model_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'publications', ['publication_id'], ['id'])
    op.drop_column('favorites', 'car_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('car_model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_car_model_id_fkey', 'favorites', 'car_models', ['car_model_id'], ['id'])
    op.drop_column('favorites', 'publication_id')
    # ### end Alembic commands ###
