"""0009_add_isactive_field

Revision ID: 3cd4f79d452b
Revises: 9868c224d768
Create Date: 2024-08-28 15:36:57.669066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '3cd4f79d452b'
down_revision: Union[str, None] = '9868c224d768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('is_active', sa.Boolean(), nullable=True))

    connection = op.get_bind()
    connection.execute(text("UPDATE publications SET is_active = TRUE"))

    op.alter_column('publications', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'is_active')
    # ### end Alembic commands ###
