"""0011_add_default_value_user_role

Revision ID: 73bf640111d9
Revises: 3cd4f79d452b
Create Date: 2024-08-29 15:18:17.857049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bf640111d9'
down_revision: Union[str, None] = '3cd4f79d452b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
