"""0010_rename_field_Favorite

Revision ID: c7b2b206523a
Revises: 21493407531f
Create Date: 2024-09-01 18:02:09.083913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b2b206523a'
down_revision: Union[str, None] = '21493407531f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('model_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorites_car_model_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'car_models', ['model_id'], ['id'])
    op.drop_column('favorites', 'car_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('car_model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_car_model_id_fkey', 'favorites', 'car_models', ['car_model_id'], ['id'])
    op.drop_column('favorites', 'model_id')
    # ### end Alembic commands ###
