"""0015_edit_max_len_CarModel_generation

Revision ID: cf04981655f5
Revises: efc6692cfdb9
Create Date: 2024-09-04 10:34:02.176141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf04981655f5'
down_revision: Union[str, None] = 'efc6692cfdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_models', 'generation',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_models', 'generation',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
