"""0003_edit_column_names

Revision ID: db53535e5aaf
Revises: e9d78b3b3e8c
Create Date: 2024-08-26 15:51:58.619122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db53535e5aaf'
down_revision: Union[str, None] = 'e9d78b3b3e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_models', 'generation',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.add_column('publications', sa.Column('publication_date', sa.TIMESTAMP(), nullable=False))
    op.drop_column('publications', 'publication_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('publication_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('publications', 'publication_date')
    op.alter_column('car_models', 'generation',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
