"""0002_edit_time_columns_types

Revision ID: e9d78b3b3e8c
Revises: c255f1af0f31
Create Date: 2024-08-26 14:22:47.425279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d78b3b3e8c'
down_revision: Union[str, None] = 'c255f1af0f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('publication_id', sa.Integer(), nullable=False))
    op.add_column('publications', sa.Column('car_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'car_year')
    op.drop_column('publications', 'publication_id')
    # ### end Alembic commands ###
