"""0014_edit_nullable_publication_car_year

Revision ID: efc6692cfdb9
Revises: 2dfe31a7eab4
Create Date: 2024-09-04 10:29:56.834807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc6692cfdb9'
down_revision: Union[str, None] = '2dfe31a7eab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'car_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'car_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
